#!/usr/bin/env bash

echo "Non usare, non crea correttamente"
exit 0

set -euo pipefail

DOCROOT="."
BASE_URL="/MAT-TSL-documentation"
OUTPUT="complete_index.md"
TMP="$(mktemp)"

# 1️⃣ copia intestazione fino alla sentinella
awk '
  { print }
  /<!-- AUTOGENERATED LINKS BELOW - DO NOT EDIT -->/ { exit }
' "$OUTPUT" > "$TMP"

echo "" >> "$TMP"

# 2️⃣ funzione per titolo leggibile
title_from_name() {
  local name="$1"
  name="${name%.md}"
  name="${name//_/ }"
  name="${name//-/ }"
  echo "${name^}"
}

# 3️⃣ genera link ricorsivamente
generate_links() {
  local dir="$1"
  local depth="$2"

  local indent=""
  for ((i=0; i<depth; i++)); do indent+="  "; done

  # index.md della directory
  if [[ -f "$dir/index.md" && "$dir" != "." ]]; then
    local rel="${dir#./}"
    echo "${indent}- [$(title_from_name "$(basename "$dir")")](${BASE_URL}/${rel}/index.html)" >> "$TMP"
  fi

  # file .md (tranne index e complete_index)
  for file in "$dir"/*.md; do
    [[ ! -f "$file" ]] && continue
    [[ "$(basename "$file")" == "index.md" ]] && continue
    [[ "$(basename "$file")" == "complete_index.md" ]] && continue

    local rel="${file#./}"
    local html="${rel%.md}.html"

    echo "${indent}  - [$(title_from_name "$(basename "$file")")](${BASE_URL}/${html})" >> "$TMP"
  done

  # sottodirectory
  for sub in "$dir"/*/; do
    [[ ! -d "$sub" ]] && continue
    generate_links "${sub%/}" $((depth + 1))
  done
}

# 4️⃣ avvio dalla root docs/
generate_links "." 0

# 5️⃣ sostituzione atomica
mv "$TMP" "$OUTPUT"

echo "✔ complete_index.md rigenerato correttamente"

